import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Sans, Inter } from 'next/font/google';
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-brand2',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap', 
  variable: '--font-brand1',
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${josefinSans.variable} ${inter.variable}`}>
      <body className="font-brand2">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
