import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function ClientThemeHandler({ children }: { children: React.ReactNode }) {
  const { theme } = useThemeContext(); // ✅ این hook فقط در کلاینت کار میکند

  return (
    <div data-theme={theme} className="h-full">
      {children}
    </div>
  );
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
